name: payslip_flutter
description: "A Flutter project for generating payslips."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: any
  shared_preferences: any
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  flutter_lints: ^5.0.0
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.1
  intl: ^0.19.0
  flutter_html: ^3.0.0-alpha.3

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/logo.png
    - assets/default_profile.png
    - assets/menu.png
    - assets/icons/home.png
    - assets/icons/attendance.png
    - assets/icons/payslip.png
    - assets/icons/leave.png
    - assets/icons/profile.png
    - assets/icons/setting.png
    - assets/icons/logout.png
    - assets/icons/edit.png
    - assets/icons/delete.png

# flutter_launcher_icons configuration should be here, at the same level as flutter
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  web: true
  windows: true
  macos: true

fonts:
  - family: GoogleSans
    fonts:
      - asset: fonts/GoogleSans-Regular.ttf
      - asset: fonts/GoogleSans-Medium.ttf
        weight: 500
      - asset: fonts/GoogleSans-Bold.ttf
        weight: 700
