name: ata_crm
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  cupertino_icons: ^1.0.8
  http: any
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0
  provider: ^6.1.2
  flutter_lints: ^5.0.0
  url_launcher: ^6.0.20
  intl: ^0.20.2
  flutter_html: ^3.0.0-alpha.3
  html_editor_plus: ^0.0.5
  file_picker: ^8.0.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  device_info_plus: ^11.1.1
  open_file: ^3.5.9
  art_sweetalert: ^0.0.5
  image_picker: ^1.1.2
  dio: ^5.7.0
  flutter_inappwebview: ^6.1.5
  flutter_downloader: ^1.11.8

  http_parser: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

  assets:
    - assets/icon/app_icon.png
    - assets/logo.png
    - assets/default_profile.png
    - assets/menu.png
    - assets/icons/home.png
    - assets/icons/attendance.png
    - assets/icons/payslip.png
    - assets/icons/leave.png
    - assets/icons/profile.png
    - assets/icons/setting.png
    - assets/icons/logout.png
    - assets/icons/edit.png
    - assets/icons/delete.png
    - assets/icons/appointments.png
    - assets/icons/leads.png
    - assets/icons/tasks.png
    - assets/icons/clients.png

