// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEeT5dY9dxzngQZv4hDTeXosuVnzrq3M',
    appId: '1:927791039254:web:bf77e1ee7431e621004637',
    messagingSenderId: '927791039254',
    projectId: 'ata-crm',
    authDomain: 'ata-crm.firebaseapp.com',
    storageBucket: 'ata-crm.firebasestorage.app',
    measurementId: 'G-YSDNX84W7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WIc0rnhb6FytNUStMETDHNJ_Ez-DV18',
    appId: '1:927791039254:android:6a514d6603ea8156004637',
    messagingSenderId: '927791039254',
    projectId: 'ata-crm',
    storageBucket: 'ata-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNkIuORny5KMtDpxY8WkAF40qURz5BVaY',
    appId: '1:927791039254:ios:2fb482b318ccbfa3004637',
    messagingSenderId: '927791039254',
    projectId: 'ata-crm',
    storageBucket: 'ata-crm.firebasestorage.app',
    iosBundleId: 'com.codewebcraft.payslip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNkIuORny5KMtDpxY8WkAF40qURz5BVaY',
    appId: '1:927791039254:ios:b0c1856813aa82f6004637',
    messagingSenderId: '927791039254',
    projectId: 'ata-crm',
    storageBucket: 'ata-crm.firebasestorage.app',
    iosBundleId: 'com.ataanalytiq.ata_crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTEeT5dY9dxzngQZv4hDTeXosuVnzrq3M',
    appId: '1:927791039254:web:6646b8aeaad7a83c004637',
    messagingSenderId: '927791039254',
    projectId: 'ata-crm',
    authDomain: 'ata-crm.firebaseapp.com',
    storageBucket: 'ata-crm.firebasestorage.app',
    measurementId: 'G-SEWMJZPCV3',
  );
}
